DROP DATABASE IF EXISTS example_db;
CREATE DATABASE example_db;
USE example_db
DROP TABLE IF EXISTS user;
CREATE TABLE user (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name TEXT NOT NULL) DEFAULT CHARACTER SET=utf8;
